### ISSUE TITLE
Major missing items

### ISSUE THREAD

**Issue by wwared** [argumentcomputer/lurk-hs#2]
- [x] Expose the plonk verification functions from [here](https://github.com/argumentcomputer/sphinx/blob/f51436fe14e6d029313546e8284cf6762f81f776/recursion/gnark-ffi/src/ffi/native.rs#L43), alternatively [replicate the build.rs logic](https://github.com/argumentcomputer/sphinx/blob/dev/recursion/gnark-ffi/build.rs) to build the Go dependency, and expose the functions in the Go library instead (handled in #3)
- [x] Add simple functions for doing the proper serialization to and from an external format usable by smart contracts and the internal format used by the FFI functions (handled in #3/#4 plus https://github.com/argumentcomputer/zk-light-clients/pull/216)
- [x] Re-calculate the committed values digest based on the public values themselves, since those are exposed to the smart contract (handled in #4)
- [x] Some sort of error handling to prevent panics in the verifier from bringing the whole application down, possibly by spawning a dedicated thread for the FFI operations
- [x] Silence the output to stdout/stderr of the underlying libraries
